#!/bin/bash

function getHelp() {
    echo 'The following parameters will define which files to consider:
    -d, --diff    Will select the files marked as edited on Git
    -s, --staged  Will select the staged files on Git
    -a, --all     Will select all the files into the folders "src" and "tests"
    --ref         Will select the files that was changed beetween the informed branch/commit/tag and HEAD
    <path/file>   Will select the files in the path informmed'
}

PARAM_FILES=
GIT_DIFF=0
GIT_STAGED=0
ALL_FILES=0
REF_FILES=0
GIT_REF=
ONLY_PHP=0

argv=("$@")
argc=${#@}
i=0
while [ $i -lt $argc ]; do
    if [[ "${argv[$i]}" == "--help" ]] || [[ "${argv[$i]}" == "-h" ]]; then
        getHelp
        exit 0
    elif [[ "${argv[$i]}" == '--php' ]]; then
        ONLY_PHP=1
    elif [[ "${argv[$i]}" == '-d' ]] || [[ "${argv[$i]}" == '--diff' ]]; then
        GIT_DIFF=1
        i=$(($i + 1))
        break
    elif [[ "${argv[$i]}" == '-s' ]] || [[ "${argv[$i]}" == '--staged' ]]; then
        GIT_STAGED=1
        i=$(($i + 1))
        break
    elif [[ "${argv[$i]}" == '-a' ]] || [[ "${argv[$i]}" == '--all' ]]; then
        ALL_FILES=1
        i=$(($i + 1))
        break
    elif [[ "${argv[$i]}" == '--ref' ]]; then
        REF_FILES=1
        if [[ ! "${argv[$i + 1]}" =~ ^- ]]; then
            GIT_REF="${argv[$i + 1]}"
            i=$(($i + 1))
        fi
        i=$(($i + 1))
        break
    elif [[ "${argv[$i]}" =~ ^- ]]; then
        break
    else
        PARAM_FILES="$PARAM_FILES ${argv[$i]}"
    fi
    i=$(($i + 1))
done

i=$(($i + 1))
echo "PARAMS=\"${@:$i}\""

[ ! -z "$PARAM_FILES" ] && {
    echo "FILES=\"${PARAM_FILES:1}\""
    exit 0
}

GREP_REGEXP="."
[ $ONLY_PHP -eq 1 ] && GREP_REGEXP="(.php|/)$"

[ $GIT_DIFF -eq 1 ] && {
    echo -n 'FILES="'
    git status --short | egrep "^R" | cut -d '>' -f 2 | egrep $GREP_REGEXP
    git status --short | egrep -v "^(R|.R|D|.D)" | cut -c 4- | egrep $GREP_REGEXP
    echo -n '"'
    exit 0
}

[ $GIT_STAGED -eq 1 ] && {
    echo -n 'FILES="'
    git diff --cached --name-only --diff-filter=ACMR HEAD | egrep $GREP_REGEXP
    echo -n '"'
    exit 0
}

[ $ALL_FILES -eq 1 ] && {
    echo 'FILES="./src
./tests"'
    exit 0
}

[ $REF_FILES -eq 1 ] && {
    [[ -z "$GIT_REF" ]] && GIT_REF=master

    echo -n 'FILES="'
    git diff-tree --diff-filter=ACMR --no-commit-id --name-only -r "$GIT_REF..HEAD" | egrep $GREP_REGEXP
    echo '"'
    exit 0
}
