#!/bin/bash

if [ -z "$1" ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
    echo \
        'This command will analyse PHP Syntax of source files based on parameters'
    ./cli/get-git-files --help
    exit
fi

eval $(./cli/get-git-files --php $@)

if [ "$FILES" == "" ]; then
    echo "Nenhum arquivo para verificar !"
    exit 0
fi

echo "--- Running Check PHP Syntax"
for FILE in $FILES; do
    php -l $FILE
    RETURN=$?
    if [ $RETURN != 0 ]; then
        exit $RETURN
    fi
done
exit 0
