#!/bin/bash

if [ -z "$1" ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
    echo \
        'This command will fix PHP source files based on parameters'
    ./cli/get-git-files --help
    exit
fi

eval $(./cli/get-git-files --php $@)

if [ "$FILES" == "" ]; then
    echo "Nenhum arquivo para verificar !"
    exit 0
fi

echo "--- Running PHP-CS-Fixer"
./server/vendor/bin/php-cs-fixer fix --config server/.php-cs --cache-file=server/.php_cs.cache $PARAMS $FILES
