#!/bin/bash

if [ -z "$1" ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
    echo \
        'This command will analyse PHP source files based on parameters'
    ./cli/get-git-files --help
    exit
fi

eval $(./cli/get-git-files --php $@)

FILES=$(echo "$FILES" | sed "s| |\n|g" | grep -v "Migrations")
if [ "$FILES" == "" ]; then
    echo "Nenhum arquivo para verificar !"
    exit 0
fi
echo "--- Running PHPCS"
./server/vendor/bin/phpcs --extensions=php --basepath=/var/www/html --standard=server/phpcs.xml $PARAMS $FILES
