#!/bin/bash

if [ -z "$1" ] || [ "$1" = '-h' ] || [ "$1" = '--help' ]; then
    echo \
        'This command will analyse PHP source files based on parameters'
    cli/get-git-files --help
    exit
fi

eval $(./cli/get-git-files --php $@)

if [ "$FILES" == "" ]; then
    echo "Nenhum arquivo para verificar !"
    exit 0
fi

echo "--- Running PHPStan"
./server/vendor/bin/phpstan analyse -c server/phpstan.neon --autoload-file=vendor/autoload.php --level max --error-format=raw $FILES | sed 's|/var/www/html/||g'
exit ${PIPESTATUS[0]}
